# Generated by Django 2.2.3 on 2019-08-29 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='active',
        ),
    ]
